// import "./patterns/creational/abstractFactory";
// import "./patterns/creational/builder";
// import "./patterns/creational/factoryMethod";
// import "./patterns/creational/prototype";
// import "./patterns/creational/singleton";
// import "./patterns/structural/adapter";
// import "./patterns/structural/bridge";
// import "./patterns/structural/composite";
// import "./patterns/structural/decorator";
// import "./patterns/structural/facade";
// import "./patterns/structural/flyweight";
// import "./patterns/structural/proxy";
import "./patterns/behavioral/chainOfResponsibility";
